### PR TITLE
Add API

### PR DESCRIPTION
**Pull request by sourTaste000**
One full, working and lightweight API, concentrated in one executable js file.
Before running the js file, please install `express` and `fs` first.
After that, you can do:
```sh
chmod +x index.js
./index.js
```

### Comparison
___
|               | sourTaste000                                                                          | D1snin                                         |
|---------------|---------------------------------------------------------------------------------------|------------------------------------------------|
| Language      | JavaScript(Can be converted to TypeScript)                                            | Kotlin                                         |
| Disadvantages | Cannot read files recursively, therefore cannot display `media/deepfakes/bigtimerush`, Hardcoded Links | Can't find any lmao (heavyweight ig)           |
| Advantages    | Lightweight, small in size                                                            | Complete, more controls when serving on server |

@EmeraldSnorlax cope its not ts lmao

### CODE REVIEW

**Comment by d1snin** [comment]
https://trollcrazy.femboy.cloud

**Comment by sourTaste000** [comment]
:trollface:

**Review by EmeraldSnorlax — CHANGES_REQUESTED** [review]
this needs a significant refactor to make maintainability not a mess, remind me tomorrow

**Comment by EmeraldSnorlax** [comment]
[please move this pull request](https://github.com/bigratmonster/api-js)

**Comment by sourTaste000** [comment]
https://github.com/bigratmonster/api-js/commit/4516a2b52311ced66f1d343a8da3b13474669272

**Pull request closed without merging**
