### PR TITLE
UI cleanup

### PR DESCRIPTION
**Pull request by smokeytube**

### CODE REVIEW

**Comment by SoNothingMC** [comment]
zach please use the repository that i made specifically for this: [bigrat.monster/3d](https://github.com/bigratmonster/3d)
(<https://github.com/bigratmonster/3d/invitations>)

**Comment by SoNothingMC** [comment]
ok nevermind i saw what was in it

**Comment by SoNothingMC** [comment]
make this into a webpage / markdown document and maybe i'll accept it..... just maybe.

**Comment by smokeytube** [comment]
you should accept it (itll be funny)

**Comment by smokeytube** [comment]
@SoNothingMC 
image

**Pull request merged**
