### PR TITLE
License bigrat.monster under the MIT License

### LINKED ISSUE #52: Licensing
This repository currently has no license. Others currently only have the [legal rights to view and fork the source code](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license) via Github's Terms of Service. Consider adding an open source license perhaps? The [MIT License](https://choosealicense.com/licenses/mit/) or the [Unlicense](https://choosealicense.com/licenses/unlicense/) may do well here, though some others like the [GPLv3](https://choosealicense.com/licenses/gpl-3.0/) may be more suitable if you wish for derivative works to remain free.

Note that this specific repository has caveats; many (if not all) of the image assets that it utilizes are unclear in original author and licensing. They should not be included under a license as they are not original works. Consider placing them in a different root folder and/or adding a standalone disclaimer if possible.

### PR DESCRIPTION
**Pull request by SoNothingMC**
TO CONTRIBUTORS: THIS REQUIRES YOUR ATTENTION AND RESPONSE. READ ON TO KNOW WHAT TO RESPOND.

---

Hi! After two years, I have finally decided to license bigrat.monster under an open-source license.

After careful considerations, I have chosen the [MIT License](https://spdx.org/licenses/MIT.html) for its simplicity and freedom.  
You can preview the changes in the [features/LICENSE](https://github.com/bigratmonster/bigrat.monster/tree/feature/LICENSE) branch.

However, you will need to agree to the license being applied to the code you wrote before I can merge the changes:

---

IF YOU AGREE TO THE LICENSE AND ACCEPT THE LICENSE APPLYING TO YOUR CODE,
PLEASE COMMENT `Yes`.

IF YOU DO NOT AGREE TO THE LICENSE AND REFUSE THE LICENSE APPLYING TO YOUR CODE,
PLEASE COMMENT `No`.

---

Once all 14 contributors (including me, excluding ImgBot) votes for yes, I can merge and apply the license.

Thank you for contributing to bigrat.monster over the years!

This pull request also closes #52.

@SoNothingMC @humboldt123 @smokeytube @kouwei32 @pseudoname23 @bigratenthusiast @ayunami2000 @DogeDevYT @DogeDevYT @EmeraldSnorlax @undeadluciel @XWasHere @aboutdavid @Dreamedc2015

### CODE REVIEW

**Comment by SoNothingMC** [comment]
Yes

**Comment by humboldt123** [comment]
Yes

**Comment by Dreamedc2015** [comment]
Yes

**Review by EmeraldSnorlax — APPROVED** [review]
Yes

**Comment by ismail1234j** [comment]
yes

**Comment by undeadluciel** [comment]
yes

**Comment by bigratenthusiast** [comment]
Yes

**Comment by DogeDevYT** [comment]
Yes

**Comment by d1snin** [comment]
No :trollface:

**Comment by smokeytube** [comment]
Yes

**Comment by pseudoname23** [comment]
Yes

**Comment by kouwei32** [comment]
Yes, MIT should be a good choice

**Comment by XWasHere** [comment]
yes

**Comment by ayunami2000** [comment]
Yes

**Comment by smokeytube** [comment]
Thwse comments are like in avengers infinity war when all of the avengers assemle

**Comment by d1snin** [comment]
> Thwse comments are like in avengers infinity war when all of the avengers assemle 

More like:

**Comment by SoNothingMC** [comment]
Hi @Doogie13 I forgot to ping you! Please read the PR description since we need your vote!

**Comment by Doogie13** [comment]
Yes

**Comment by aboutdavid** [comment]
Yes

**Comment by SoNothingMC** [comment]
Thanks everyone!

**Comment by undeadluciel** [comment]
yes.

**Pull request merged**
