### PR TITLE
bigrat.monster rest api

### PR DESCRIPTION
**Pull request by d1snin**
Note that this application simply takes the local bigrat.monster repository and extracts a random image from the media folder from it, and then __simply inserts the name of this image into the URL template__, which is stored in the media_config.json file, on the one hand it even makes the code faster, we do not make any requests to github, although on the other hand we need a better solution, since this affects the performance of the code if your local repository is not identical to the repository on github, by the way, you can only access the random file in the media folder, when, for example, there is no access to the media/monkeys folder. but I will add the ability to get access via query parameters in the next versions of this module.

### CODE REVIEW

**Comment by d1snin** [comment]
At the expense of launching the rest api, you should probably use something like cloudflare workers, if they allow you to run this thing there, or if you have some kind of hosting

**Review by SoNothingMC — APPROVED** [review]
Based.

**Comment by d1snin** [comment]
Don't merge yet, he doesn't want to start from gradle task :(

**Comment by EmeraldSnorlax** [comment]
cloudflare workers requires special service workers written in js / ts / rust / cpp.

**Review by EmeraldSnorlax — CHANGES_REQUESTED** [review]
cloudflare workers cant run js

**Comment by d1snin** [comment]
> cloudflare workers cant run java

what can i do.

**Comment by EmeraldSnorlax** [comment]
port it to ts :trollface:

**Comment by d1snin** [comment]
troll crazy

**Comment by smokeytube** [comment]
why cant you use .net

**Comment by NepNep21** [comment]
why .net?

**Comment by d1snin** [comment]
> why cant you use .net

.net is illegal in Russia

**Comment by d1snin** [comment]
Well, if cloudflare workers can't run such a lightweight application, then this will not be a good option for deployment

**Comment by smokeytube** [comment]
> why .net?

because it is really well supported and cool and stuff

**Comment by EmeraldSnorlax** [comment]
i will personally all people that have ever written C# from this repo

**Comment by smokeytube** [comment]
i have no fucking idk what means

**Review by XWasHere — COMMENTED** [review]
i do not know how to read

**Review by XWasHere — APPROVED** [review]

**Comment by smokeytube** [comment]
api when

**Comment by d1snin** [comment]
when

**Comment by d1snin** [comment]
i will close this pr immediately and will do a rewrite, reopen soon :flushed:

**Comment by smokeytube** [comment]
@everyone 😎

**Comment by SoNothingMC** [comment]
are you dumb

**Comment by literally1984** [comment]
> i will close this pr immediately and will do a rewrite, reopen soon 😳

😭 😭

**Comment by EmeraldSnorlax** [comment]
dead chat xd

**Comment by d1snin** [comment]
> > i will close this pr immediately and will do a rewrite, reopen soon flushed
> 
> sob sob

this is literally still in my to-do list (it's huge)

come back here in 1-2 years ig

**Pull request closed without merging**
