### PR TITLE
Created the unpleasant gradient page

### PR DESCRIPTION
**Pull request by smokeytube**

### CODE REVIEW

**Comment by smokeytube** [comment]
I didn't touch the /printer folder?

**Comment by smokeytube** [comment]
Mister Sonothing may you review these changes?

**Comment by smokeytube** [comment]
请查看这些更改Please

**Comment by SoNothingMC** [comment]
> 请查看这些更改Please

smh put javascript.txt back or i am not merging this 😡

**Comment by smokeytube** [comment]
Oh right sorry

**Pull request merged**
